services:
  mysql:
    container_name: mysql
    image: quay.io/debezium/example-mysql:2.6
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=mysqlpwdroot
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpwd
