{
 "title": "SynchDB Oracle Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Streaming Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "New panel",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "# SynchDB Oracle Connector Metrics\n\nThis is the SynchDB Oracle Connector Metrics with the following categories\n* steeaming Metrics\n* snapshot Metrics\n* schema history metrics"
   }
  },
  {
   "title": "Total Events Seen",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_totalnumberofeventsseen{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Events Skipped",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_numberoferroneousevents{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Events Filtered",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_numberofeventsfiltered{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Commits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_numberofcommittedtransactions{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Rollbacks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_numberofrolledbacktransactions{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Bad Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_abandonedtransactioncount{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of INSERTs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_totalnumberofcreateeventsseen{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of UPDATEs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_totalnumberofupdateeventsseen{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of DELETEs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_totalnumberofdeleteeventsseen{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Queue Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_queuetotalcapacity{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Queue Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_queueremainingcapacity{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_connected{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_committhroughput{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current SCN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_currentscn{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offset SCN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_offsetscn{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Committed SCN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_committedscn{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Large Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_numberofoversizedtransactions{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Millisecond Behind Source",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_millisecondsbehindsource{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min Mined Log Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_minimumminedlogcount{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Batch Processing Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_averagebatchprocessingthroughput{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Millisecond Since Last Event",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_millisecondssincelastevent{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Captured DMLs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_totalcaptureddmlcount{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Mined Log Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_maximumminedlogcount{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_errorcount{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Switch Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_logswitchcount{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LogMiner Query Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_fetchingquerycount{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Snapshot Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Total Table Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_totaltablecount{instance=\"$instance\", context=\"snapshot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Tables",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_remainingtablecount{instance=\"$instance\", context=\"snapshot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_snapshotdurationinseconds{instance=\"$instance\", context=\"snapshot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Milliseconds Since Last Snapshot Event",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_millisecondssincelastevent{context=\"snapshot\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_totalnumberofeventsseen{instance=\"$instance\", context=\"snapshot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Milliseconds Since Last Event",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_millisecondssincelastevent{instance=\"$instance\", context=\"snapshot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Queue Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_queueremainingcapacity{instance=\"$instance\", context=\"snapshot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_snapshotrunning{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot Aborted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_snapshotaborted{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot Completed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_snapshotcompleted{instance=\"$instance\", context=\"snapshot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Schema History Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Recovery Start Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_recoverystarttime{instance=\"$instance\", context=\"schema-history\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Milliseconds Since Last Recovery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_millisecondssincelastrecoveredchange{instance=\"$instance\", context=\"schema-history\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Milliseconds Since Last Applied Change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_millisecondssincelastappliedchange{instance=\"$instance\", context=\"schema-history\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Changes Recovered",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_changesrecovered{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Changes Applied",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "debezium_oracle_connector_metrics_changesapplied{instance=\"$instance\", context=\"schema-history\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}