{
 "title": "SynchDB MySQL Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Binlog Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "New panel",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "# SynchDB MySQL Connector Metrics\n\nThis is the SynchDB MySQL Connector Metrics with the following categories\n* binlog Metrics\n* snapshot Metrics\n* schema history metrics"
   }
  },
  {
   "title": "Connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_connected{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Binlog Position",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_binlogposition{context=\"streaming\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GTID Enabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_isgtidmodeenabled{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Commits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_numberofcommittedtransactions{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Rollbacks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_numberofrolledbacktransactions{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Bad Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_numberofnotwellformedtransactions{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Events Seen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_totalnumberofeventsseen{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Events Skipped",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_numberofskippedevents{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Events Filtered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_numberofeventsfiltered{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of INSERTs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_totalnumberofcreateeventsseen{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of UPDATEs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_totalnumberofupdateeventsseen{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of DELETEs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_totalnumberofdeleteeventsseen{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Queue Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_queuetotalcapacity{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Queue Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_queueremainingcapacity{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Milliseconds Behind Source",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_millisecondsbehindsource{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Large Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_numberoflargetransactions{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Milliseconds Since Last Streaming Event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_millisecondssincelastevent{context=\"streaming\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Snapshot Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total Table Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_totaltablecount{instance=\"$instance\", context=\"snapshot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Tables",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_remainingtablecount{instance=\"$instance\", context=\"snapshot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_snapshotdurationinseconds{instance=\"$instance\", context=\"snapshot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Milliseconds Since Last Snapshot Event",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_millisecondssincelastevent{context=\"snapshot\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_totalnumberofeventsseen{instance=\"$instance\", context=\"snapshot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Milliseconds Since Last Event",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_millisecondssincelastevent{instance=\"$instance\", context=\"snapshot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Holding Global Lock",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_holdinggloballock{instance=\"$instance\", context=\"snapshot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_snapshotrunning{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot Aborted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_snapshotaborted{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot Completed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_snapshotcompleted{instance=\"$instance\", context=\"snapshot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Schema History Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Recovery Start Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_recoverystarttime{instance=\"$instance\", context=\"schema-history\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Milliseconds Since Last Recovery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_millisecondssincelastrecoveredchange{instance=\"$instance\", context=\"schema-history\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Milliseconds Since Last Applied Change",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_millisecondssincelastappliedchange{instance=\"$instance\", context=\"schema-history\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Changes Recovered",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_changesrecovered{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Changes Applied",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "debezium_mysql_connector_metrics_changesapplied{instance=\"$instance\", context=\"schema-history\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}